# Generated by Django 3.2.9 on 2022-02-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220207_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
