# Generated by Django 3.2.9 on 2022-02-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='head',
        ),
    ]
